### ISSUE TITLE
AttributeError: 'PosixPath' object has no attribute 'with_stem'

### ISSUE THREAD

**Issue by fcollingwood** [UNUF/TFTTool#2]
Replace "ansi" with "utf-8" to get past the previously reported issue. Now I have this:

frank@debian:~/Downloads$ python3 TFTTool.py -i NanoDLP1.2.1-TFT/3.5inch-basic1.2.1.tft -t TJC4832T035
Traceback (most recent call last):
  File "TFTTool.py", line 732, in <module>
    outputPath = tftPath.with_stem(tftPath.stem + "_" + args.target)
AttributeError: 'PosixPath' object has no attribute 'with_stem'

**Comment by fcollingwood** [comment]
I get the same if I include the _011 suffix:

frank@debian:~/Downloads$ python3 TFTTool.py -i NanoDLP1.2.1-TFT/3.5inch-basic1.2.1.tft -t TJC4832T035_011
Traceback (most recent call last):
  File "TFTTool.py", line 732, in <module>
    outputPath = tftPath.with_stem(tftPath.stem + "_" + args.target)
AttributeError: 'PosixPath' object has no attribute 'with_stem'
