### ISSUE TITLE
Conversion error between same resolution screens 

### ISSUE THREAD

**Issue by VK4GHZ** [UNUF/TFTTool#3]
Trying to convert from t035 to t135, but won't allow cross series conversion.
Both these screens are the same resolution, 480 x 320px.

I'm not 100% sure if I have created the t135 2XOR Key properly, as follows;

Value 1 from .tft file Total File Length found at offset 3c 3d 3e 3f 
Total file length =  740a0400

Value 2 from TFTTool output Header2 user code length
usercodeLength = 47c7266b

I input both values into online XOR calculator;
http://xor.pw/#

The result = 33cd226b
I then added this as the 2XOR key for the T135 into the TFTTool.py script.

New line looks like this:
        "TJC4832T135_011": 0x33cd226b, 

TFTTool output:

C:\Temp\TFTTool>python tfttoolv2.py -i tjc4832t035_011.tft -t tjc4832t135_011
Traceback (most recent call last):
  File "C:\Temp\TFTTool\tfttoolv2.py", line 730, in <module>
    tft.setModel(args.target, args.force)
  File "C:\Temp\TFTTool\tfttoolv2.py", line 624, in setModel
    raise Exception("Cannot convert to a model with different resolution or from a different series.")
Exception: Cannot convert to a model with different resolution or from a different series.

**Comment by MMMZZZZ** [comment]
Hi @VK4GHZ,

Sorry for the late reply; I had my notifications not yet activated for this project... 

The reason for the error is that although the device names suggest them to be similar, they are actually quite different. They come with different features and in consequence different (incompatible) bootloaders. For that reason you cannot convert between T0 and T1 just like you can't convert between T0 and X5. 

It would take significant progress in the TFT reverse engineering to enable such conversions. However, there's currently nobody actively working on the TFT reverse engineering AFAIK (as for myself, I don't have the time to continue the work significantly). 

Kind regards,
Max
