### ISSUE TITLE
Does not support new editor versions

### ISSUE THREAD

**Issue by klack** [UNUF/TFTTool#7]
It appears that this tool does not work on later editor versions.  I get the following error:
```
python .\TFTTool.py -i tenlog.HMI -o tenlog.txt
usage: TFTTool.py [-h] -i TFT_FILE [-o OUTPUT_FILE] [-t TARGET] [-e EDITOR_VERSION] [--header2 HEADER2] [-f] [-v]
TFTTool.py: error: Invalid source file!
PS C:\Users\rlayt\Downloads\TFTTool-main\TFTTool-main> python .\TFTTool.py -i tenlog.HMI -o tenlog.txt
Traceback (most recent call last):
  File "C:\Users\rlayt\Downloads\TFTTool-main\TFTTool-main\TFTTool.py", line 720, in <module>
    tft = TFTFile(f.read(), header2_hint=args.header2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rlayt\Downloads\TFTTool-main\TFTTool-main\TFTTool.py", line 517, in __init__
    version_str = self.getEditorVersionStr()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rlayt\Downloads\TFTTool-main\TFTTool-main\TFTTool.py", line 533, in getEditorVersionStr
    vendor = {ord("T"): "tjc", ord("N"): "nxt"}[self._getVal("editor_vendor")]
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
```

**Comment by kellybyrd** [comment]
PR #8  should fix the version problem. But your cmdline seems to be using HMI files as input. This code is built for TFT files.

**Comment by klack** [comment]
Its great to see someone putting some active work into this.
